---
# Source: shop-umbrella-blue-green/charts/discounts-blue/charts/quarkus-base/templates/configmap-env-base.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: "discounts-configmap-env-base"
  labels:
    helm.sh/chart: quarkus-base-0.1.0
    app.kubernetes.io/name: discounts-umbrella
    app.kubernetes.io/instance:  {{ .Release.Name }}
    app: discounts
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
data:
  application.version: v1.0.1
  application.colour: none
  
  quarkus.log.level: DEBUG

  # quarkus.http.ssl-port: "8443"
  # quarkus.http.ssl.certificate.file: "/var/run/secret/kubernetes.io/ssl/cert.pem"
  # quarkus.http.ssl.certificate.key-file: "/var/run/secret/kubernetes.io/ssl/key.pem"

  quarkus.jaeger.service-name: "discounts"
  quarkus.jaeger.sampler-type: "const"
  quarkus.jaeger.sampler-param: "1"
  quarkus.jaeger.endpoint: "http://jaeger-collector.gitops.svc:14268/api/traces"
  quarkus.jaeger.propagation: "b3"
  quarkus.jaeger.reporter-log-spans: "true"
---
# Source: shop-umbrella-blue-green/charts/discounts-blue/templates/configmap-env.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: "discounts-configmap-env"
  labels:
    helm.sh/chart: discounts-blue-0.1.0
    app.kubernetes.io/name: discounts-umbrella
    app.kubernetes.io/instance:  {{ .Release.Name }}
    app: discounts-umbrella
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
data:
  application.mode: online