apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: products
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: gitops-test
    server: 'https://kubernetes.default.svc'
  source:
    path: helm/quarkus-helm-products/chart
    repoURL:  https://github.com/pacaruso/cloud-native-deployment-strategies.git
    targetRevision: canary-experiment
    helm:
      parameters:
      - name: "global.namespace"
        value: gitops-test
      valueFiles:
        - values/values-canary-rollouts.yaml
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true