apiVersion: v1
kind: ConfigMap
metadata:
  name: "products-configmap-env-base"
  labels:
    helm.sh/chart: quarkus-base-0.1.0
    app.kubernetes.io/name: products
    app.kubernetes.io/instance:  {{ .Release.Name }}
    app: products
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
data:
  application.version: {{.Values.global.image.tag }}
  application.colour: none
  
  quarkus.log.level: DEBUG

  # quarkus.http.ssl-port: "8443"
  # quarkus.http.ssl.certificate.file: "/var/run/secret/kubernetes.io/ssl/cert.pem"
  # quarkus.http.ssl.certificate.key-file: "/var/run/secret/kubernetes.io/ssl/key.pem"

  quarkus.jaeger.service-name: "products"
  quarkus.jaeger.sampler-type: "const"
  quarkus.jaeger.sampler-param: "1"
  quarkus.jaeger.endpoint: "http://jaeger-collector.gitops.svc:14268/api/traces"
  quarkus.jaeger.propagation: "b3"
  quarkus.jaeger.reporter-log-spans: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "products-configmap-env"
  labels:
    helm.sh/chart: products-blue-0.1.0
    app.kubernetes.io/name: products
    app.kubernetes.io/instance:  {{ .Release.Name }}
    app: products
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
data:
  application.mode: online 

  quarkus.rest-client.discounts-api.url: http://discounts-online:8080
  quarkus.rest-client.discounts-api.scope: javax.inject.RequestScoped
  #quarkus.rest-client.discounts-api.connection-pool-size: "50"
  quarkus.rest-client.discounts-api.connection-ttl: "1"