tags:
  discounts-green: false
  products-green: false
  discountsNetworkingOffline: false
  productsNetworkingOffline: false

global:
  namespace: test
  #needed for rollouts analysis
  prometheusAddress: https://prometheus-user-workload.openshift-user-workload-monitoring.svc.cluster.local:9091
  mode: online
  image:
    tag: v1.0.1
  version: none
  replicaCount: 4
  fullnameOverride: "products"
  rollouts:
    enabled: true
    analysis:
      web: true
      service: "products-online"
    canary:
      steps:
        - setWeight: 10
        - pause: {}
        - setWeight: 50
        - pause:
            duration: 30s
